### PR TITLE
Fix tulip plant ids.

### PR DESCRIPTION
**Pull request by Dilnu**

### CODE REVIEW

**Comment by InfinityRaider** [comment]
I do not really understand what these changes achieve...

**Comment by TokkenGmr** [comment]
It looks like the reformat that was done 2 months ago changed the "path name" however the  "id" was left unchanged.  
"path": "vanilla/plants/orange_tulip_plant.json"
"id": "orangetulip_plant"
should be 
"id": "orange_tulip_plant"

**Comment by Dilnu** [comment]
The botania mystical flower mutations are broken because they assume these are the plant ids.

**Comment by TokkenGmr** [comment]
Not sure how botania is broken by this. The Repo does not show them being needed in botania mutations

**Comment by Dilnu** [comment]
Oh, that must be my custom mutations. I copied over the 1.7 default mutations for a bunch of things.

**Comment by TokkenGmr** [comment]
Yeah when I first created the vanilla flowers I thought about using the scripts from Infinity evolved expert mode from 1.7.10 as well but then I thought those mutations were intended for an "expert" mode. So they are based off of the non-expert version that way it doesn't feel grindy to the average person.

**Comment by Dilnu** [comment]
If there isn't a default I used the ones from regrowth.

**Pull request merged**
