### PR TITLE
Upgrade Aquatic compatibility

### PR DESCRIPTION
**Pull request by nbrichau**

### CODE REVIEW

**Comment by InfinityRaider** [comment]
The mod is update aquatic, but none of the plants are water based?

**Comment by nbrichau** [comment]
Unless I missed something, the jsons should be good. The pickerelweeds and kelps need to be planted in water, and searockets on sand.
Did you mean something else by "water based"?

**Comment by InfinityRaider** [comment]
No I expected all of them to need to be under water, but then again, I am not familiar with the mod.

**Comment by nbrichau** [comment]
Ok, everything is working as intended then.

**Pull request merged**
