### PR TITLE
use melon and pumpkin textures (#782)

### PR DESCRIPTION
**Pull request by inversemot**
Fix for #782

### CODE REVIEW

**Comment by RlonRyan** [comment]
Looks good, thanks!

**Comment by inversemot** [comment]
Looking at previous versions, this is more like a hack than a fix. I didn't realize that they used to have a better model. But it does look much better like this than wheat.

**Comment by RlonRyan** [comment]
The gourd renderer hasn't been implemented yet, so this is the proper fix for now.

**Comment by inversemot** [comment]
I'd be happy to try to implement it, but there's a lot of indirection between the crop spec files and where everything gets used. For instance I'm not sure where the JSON gets parsed. It looks like I need to fill out the getSecondaryTexture (or whatever it's called) so that the stem case can use it. But I could really do with a flowchart or something.

**Comment by InfinityRaider** [comment]
the json has like a rendermethod, crossed or hashtag, can also be Gourd.
And indeed, that is what the secondary texture is used for.

**Pull request merged**
