### PR TITLE
Add Silicon Plant json

### PR DESCRIPTION
**Pull request by darthvader45**
Added json to AgriPlants to enable placing of silicon seeds on Agricraft crop sticks.

### CODE REVIEW

**Comment by darthvader45** [comment]
Should be pretty much bug-free, if any bugs let me know.

**Comment by RlonRyan** [comment]
Thanks!

**Comment by darthvader45** [comment]
Works correctly, I assume?

**Comment by TokkenGmr** [comment]
This was also added in the PR I did back in Oct. They both got merged

**Comment by RlonRyan** [comment]
Yeah, I didn't notice the conflict at first, but I have removed one of them since then.

**Comment by darthvader45** [comment]
Okay, let me know if anything else json related turns up.  I can churn out json files on a whim now.

**Comment by RlonRyan** [comment]
Thanks, will do!

**Pull request merged**
