### PR TITLE
Crop sticks Fixes and Compatibility for Hatchery, Farming For Blockheads, Snad, and Mystical Agriculture

### PR DESCRIPTION
**Pull request by raziel23x**
…mysticalagriculture crop seeds

* Fixed Crop sticks to now work with hatchery fertilized farmland
* Fixed Crop sticks to now work with hatchery fertilized dirt
* Fixed inferium seeds tier 1-6 can't be planted in crop sticks

### CODE REVIEW

**Comment by raziel23x** [comment]
These are some changes I have made to fix issues with my Sky Laboratory-Remade modpack i am working on to make things work with other soils i am using since i am using the feature disable vanilla farming and thought to share these changes

**Comment by raziel23x** [comment]
more fixes added found that the end steel seed was missing and was not working with the crop sticks as well

**Comment by raziel23x** [comment]
Okay went though each json file one at a time and added in the new farmland and soil types to the correct crops

**Comment by raziel23x** [comment]
found another missing seed from mysticalagriculture

**Comment by raziel23x** [comment]
added snad Support to crops and crop sticks

**Comment by raziel23x** [comment]
Sorry for the multiple commits for this pull request but i have tested out everything so far looks good and working on my test world so i think this pull request has been fully tested and working and finished with updates for this PR hopefully this will get approved soon

**Comment by raziel23x** [comment]
last night i noticed this file kept appearing every time i loaded up the mod pack zinc_plant - Copy.json and its a exact copy of zinc_plant.json and it seems the last update to the mod someone added this file by mistake, at first i thought it was something i did but when i would delete it and run the mod again it would show up

**Comment by raziel23x** [comment]
found that dragon egg seeds was missing today

**Comment by RlonRyan** [comment]
@InfinityRaider It does seem like it would work, although I'm realizing that i'm little concerned with the way that I setup soils, as ideally any mod-specific soils wouldn't be referenced from vanilla plant definitions. I almost wonder if I should have setup a method to append to other configuration files, so that each mod config group could be isolated but update others as needed. The problem with that however is that it would then become impossible to track down what is modifying what where. Perhaps updating the farmland_soil definition would be an alternate way of doing this, as then there would be fewer spots that need updated in the event something changed, but that wouldn't for different growth rates with fertilized farmland soil. I guess what is needed here is something like a soil group, that you could join as needed, so that if you had a soil that is essentially the same as farmland you could join the farmland soil group and anything that supports that group would support your soil.

My original concept for soils used a constraint-based system, where a soil would have certain attributes, and a plant would require certain soil attributes, and would accept any soil that met those attributes, which would allow the plants to be configured without having any links to soils, simplifying a lot of things. Perhaps that is more of a future version thing.

**Comment by raziel23x** [comment]
yeah that would help lots when different soils are added from crop type mods

**Comment by raziel23x** [comment]
This would be something that would work well with 1.14.X i have not fully looked at the code but it seems it would work best for the latest build of minecraft but with the way forge is right now and also the fact that Fabric API is trying to compete with forge i am on the fence to which way you could go with which API to use to get the wanted results

**Comment by InfinityRaider** [comment]
I realize that it has been quite a while, and this is probably a longshot but as I am currently workign on 1.16, I might do one more release for 1.12 with all the PRs that have been made to agricraft and agriplants.
However since there is a significant amount of conflicts in this one, therefore I will not merge this unless you can take care of the conflicts, as all my spare time goes into development for 1.16 currently.

**Comment by InfinityRaider** [comment]
Closing due to inactivity.

**Pull request closed without merging**
