### PR TITLE
Add 75 of the Mystical Agriculture plants

### PR DESCRIPTION
**Pull request by dshadowwolf**
This adds the default Mystical Agriculture plants, plus the ones available when EnderIO and Thermal Expansion are installed. There are more plants - IIRC, Mystical Agriculture also covers, at least, Extreme Reactors, though I do not have the rest of those mods available.

I have a quick&dirty piece of NodeJS code for pulling in a template and a list of crops and producing the output plants - its easily extended and I'll make it available on request

### CODE REVIEW

**Comment by TokkenGmr** [comment]
I think the soil should be changed to gravel that way it would be similar to the default resource crops soil. Just my thought .

**Comment by dshadowwolf** [comment]
Mystical Agriculture, by default, uses "farmland" - no reason to change that. And this is only a subset as I don't have all the supported mods loaded

**Comment by TokkenGmr** [comment]
Almost all crops use "farmland" by default, until Agricraft is added to the mix. I was just suggesting it to keep things consistent. Seeing how resource crops like Iron and Diamond that are added by Agricraft use gravel. Even if you choose to use diamond crops from Mystical Agriculture, it makes sense to have it be the same.

**Comment by dshadowwolf** [comment]
I have found a small issue with the textures for the seed items - I'll be looking into fixing that sometime before the weekend

**Comment by dshadowwolf** [comment]
I think that should solve the issues with the seeds being referred to with incorrect names and get some of the other bits that were lacking more correct.

**Comment by RlonRyan** [comment]
Thank you so much for providing these JSON files, we've had lots of requests for AgriCraft to support Mystical Agriculture but I haven't the time to learn all the plants in the mod as to do the compat myself. This is a big help.

**Comment by RlonRyan** [comment]
If you can tell me when this is good to merge, that would be great! Hopefully, it can be one of the headline features of the next alpha release of AgriCraft.

**Comment by dshadowwolf** [comment]
I need to see if I can figure out what is causing the last 5 "can't find the texture" issues I'll give a signed-off

**Comment by dshadowwolf** [comment]
Alright, this is ready to go for the 75 plants I've got active in my current pack.

If you need it:
Signed-Off-By: Daniel Hazelton <dshadowwolf@gmail.com>

**Comment by RlonRyan** [comment]
By the way, you had all the plant_ids set to the same thing... they are supposed to be unique identifiers for the plant.

**Comment by dshadowwolf** [comment]
...then... *facepalm* I have a logic error in my code making the creation of the one template variable result in "undefined"

**Pull request merged**
