### PR TITLE
Botania flowers

### PR DESCRIPTION
**Pull request by Tsukiumy**

### CODE REVIEW

**Comment by RlonRyan** [comment]
This looks like a great start!

Thank you so much for providing these!
I'm not sure I would have gotten around to doing them myself...

**Comment by InfinityRaider** [comment]
The textures are still available then?

**Comment by RlonRyan** [comment]
Yup. I never removed them.

I just have to do some quick reformatting on the files before I make a new alpha...

**Comment by Tsukiumy** [comment]
ty for the better description for then, im not the best when it comes to things like this, i will try to make the ars magica one, as it is much less flowers, i just need to learn a bit about it so i dont make use of somenthing too silly

**Pull request merged**
