### PR TITLE
HarvestCraft Item ID Fix

### PR DESCRIPTION
**Pull request by TokkenGmr**
Should fix issue from [#988](https://github.com/AgriCraft/AgriCraft/issues/988)
Harvestcraft went to lowercase ids in latest update, changed  Item to item

### CODE REVIEW

**Comment by bibo38** [comment]
Tip: You can add a direct reference by adding the Issue URL instead of #988. Then Github will link it correctly and this PR is visible on the issue page 😏 .

**Comment by TokkenGmr** [comment]
@bibo38 I know I just forget to add the url when its a branch, seeing how otherwise it picks the issue up fine in the main branch. Just a lil brain fart on my part. thank you for the reminder.

**Comment by CodesCubesAndCrashes** [comment]
Mm, I think the reason GitHub didn't auto-link the text \#988 to the issue that TokkenGmr wanted was because the numbers are specific to their repository. That's an AgriCraft/AgriCraft issue, and this is a AgriCraft/AgriPlants pull request. If there was an issue/pull-request/etc with the number 988 in this AgriPlants repo, then GitHub would have auto-linked to that instead. At least I think that's how it works. The exception or quirky part is if a repo is a fork. In that case, numbers will prioritize linking to the current repo, but fall back to linking to the parent repo if that number isn't in use. [Example](https://github.com/CodesCubesAndCrashes/AgriCraft/issues/1#issue-240497268). I haven't tested yet if the linking happens at the time of the edit, or if it's dynamic, so that once enough new issues are created, the link will change what it points at. I *could* test it. But I haven't. ;)

**Comment by RlonRyan** [comment]
Seems good to me. I suppose this will get easier in 1.11 when lowercase IDs are enforced...

**Pull request merged**
